config/routes.rb
Rails.application.routes.draw do

  get 'todos', to: 'todos#index'

  get 'todos/new'

  get 'todos/list'

  post 'todos', to: 'todos#create'

  get 'todos/:id', to: 'todos#show', as: 'todo'

  get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'

  patch 'todos/:id', to: 'todos#update'

  delete 'todos/:id', to: 'todos#destroy', as: 'delete_todo'

  get 'todos/:id/complete', to: 'todos#complete', as: 'complete_todo'

  root 'todos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    todo = Todo.new(todo_params)
    if todo.description == ""
      redirect_to todos_new_path, notice: 'No puede tener un nombre en blanco'
      return
    end
    if todo.save
      # Por convencion REST, al decir que redirija a post lleva a su SHOW
      redirect_to root_path, notice: 'Se creo con exito :)'
    else
      redirect_to todos_new_path, notice: 'No se creo po :('
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      redirect_to root_path, notice: 'Se actualizo con exito'
    else
      redirect_to edit_todo(@todo.id), notice: 'No se pudo actualizar'
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to root_path, notice: 'El ToDo se ha eliminado con exito'
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save
    redirect_to root_path
  end

  def list
    @todos = Todo.all
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js" integrity="sha384-feJI7QwhOS+hwpX2zkaeJQjeiwlhOP+SdQDqhgvvo1DsjtiSQByFdThsxO669S2D" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">ToDos</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><%= link_to 'INDEX', root_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'LIST', todos_list_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'NEW', todos_new_path, class: 'nav-link' %></li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>EDIT</h1>

<h2><%= notice %></h2>

<%= form_with(model: @todo, local: true) do |form| %>
  <!-- quedan con el scope de post -->
  <%= form.label :description %>
  <%= form.text_field :description %>
  <br>
  <%= form.label :completed %>
  <%= form.check_box :completed%>
  <br>
  <%= form.submit 'Actualizar' %>
<% end %>

app/views/todos/index.html.erb
<h1>INDEX</h1>

<h2><%= notice %></h2>

<%= link_to 'Crear nuevo ToDo', todos_new_path %>

<h5>ToDos</h5>
<table>
  <tr>
    <th>Descripcion</th>
    <th>Completado</th>
    <th>Accion</th>
  </tr>
  <% @todos.each do |t| %>
  <div class="card">
    <tr>
      <td><%= link_to t.description, todo_path(t.id) %></td>
      <!-- <td><%= t.description %></td> -->
      <% if t.completed == true %>
        <td>☑</td>
      <% else %>
        <td>☐</td>
      <% end %>
      <td><%= link_to 'editar', edit_todo_path(t) %></td>
      <td><%= link_to 'eliminar', delete_todo_path(t), method: :delete %></td>
      <% if t.completed == false %>
      <td><%= button_to "completar", complete_todo_path(t), :method => "get" %></td>
      <% end %>
    </tr>
  </div>
  <% end %>
</table>

app/views/todos/list.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <table>
        <tr>
          <th>Sin completar</th>
        </tr>
        <% @todos.each do |todo| %>
        <tr>
          <% if todo.completed == false %>
          <td><%= todo.description %></td>
          <% end %>
        </tr>
        <% end %>
      </table>
    </div>
    <div class="col-sm-6">
      <table>
        <tr>
          <th>Completados</th>
        </tr>
        <% @todos.each do |todo| %>
        <tr>
          <% if todo.completed == true %>
          <td><%= todo.description %></td>
          <% end %>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<h1>NEW</h1>

<h2><%= notice %></h2>

<h5>Crear un nuevo ToDo</h5>

<%= form_with(model: @todo, local: true) do |form| %>
  <!-- quedan con el scope de post -->
  <%= form.label :description %>
  <%= form.text_field :description%>
  <br>
  <%= form.submit 'Crear' %>
<% end %>

app/views/todos/show.html.erb
<h1>SHOW</h1>
<h5><%= notice %></h5>

<table>
  <tr>
    <td><%= @todo.description %></td>
    <% if @todo.completed == true %>
      <td>☑</td>
    <% else %>
      <td>☐</td>
    <% end %>
  </tr>
</table>